version: '3'
services:
  masquerade:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    container_name: masquerade
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: dotnet run
    ports:
      - 20000:20000
    depends_on:
      - PgMaskingProxyDB

  PgMaskingProxyDB:
    image: postgres:9.6.10
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_data
    container_name: PgMaskingProxyDB
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

